name: test

on:
  push:
    branches: [ "test" ]
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'git@github.com:qdwang/jxlbridge.git'

      - name: Check
        run: ls
