name: test

on:
  push:
    branches: [ "test" ]
  workflow_dispatch:

jobs:
  build_test:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: qdwang/jxlbridge
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          path: jxlbridge

      - name: build-libjxl
        run: ./build-libjxl.sh

      - name: Check
        run: ls

      - name: Compress
        run: |
          7z a -t7z -p'${{ secrets.ARTIFACTS_PWD }}' -mhe=on -mx=9 cjxl.7z libjxl-main-macos/tools/cjxl

      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          path: cjxl.7z


