name: test

on:
  push:
    branches: [ "test" ]
  workflow_dispatch:

env:
  EXE: cjpegli

jobs:
  build_on_win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: qdwang/jxlbridge
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          path: jxlbridge
      
      - name: build-libjxl
        run: .\build-libjxl-win.bat
      
      - name: Encrypt
        run: 7z a -t7z -p'${{ secrets.ARTIFACTS_PWD }}' -mhe=on -mx=9 win.7z .\libjxl-main-windows\tools\Release\cjpegli.exe

      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          path: win.7z
          name: win
  
  build_on_mac:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: qdwang/jxlbridge
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          path: jxlbridge

      - name: build-libjxl
        run: ./build-libjxl-mac.sh

      - name: Check
        run: ls

      - name: Sign zip
        env:
          TARGET: libjxl-main-macos/tools/cjpegli
        run: |
          echo "${{ secrets.MACOS_CERT }}" | base64 -d > certificate.p12  
          security create-keychain -p "${{ secrets.ARTIFACTS_PWD }}" build.keychain 
          security default-keychain -s build.keychain
          security unlock-keychain -p "${{ secrets.ARTIFACTS_PWD }}" build.keychain
          security import certificate.p12 -k build.keychain -P "${{ secrets.MACOS_CERT_PWD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "${{ secrets.ARTIFACTS_PWD }}" build.keychain

          codesign --options runtime --force --timestamp --deep --sign "${{ secrets.WWDRTEAMID }}" $TARGET
          ditto -c -k --sequesterRsrc --zlibCompressionLevel 9 $TARGET ${{ env.EXE }}.zip

          xcrun notarytool store-credentials "OLG" --apple-id "${{ secrets.APPLE_ID }}" --team-id "${{ secrets.WWDRTEAMID }}" --password "${{ secrets.APPLEID_APP_PWD }}"
          xcrun notarytool submit ${{ env.EXE }}.zip --keychain-profile "OLG" --wait

      - name: Encrypt
        run: 7z a -t7z -p'${{ secrets.ARTIFACTS_PWD }}' -mhe=on -mx=9 mac.7z ${{ env.EXE }}.zip

      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          path: mac.7z
          name: mac


