name: test

on:
  push:
    branches: [ "libjxl" ]
  workflow_dispatch:

jobs:
  build_on_win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: build-libjxl
        run: .\build-libjxl-win.bat
      
      - name: Check
        run: |
          cd .\libjxl-main-native\lib\
          dir
          cd Release
          dir
          
      - name: Encrypt
        run: 7z a -t7z -p'${{ secrets.ARTIFACTS_PWD }}' -mhe=on -mx=9 libjxl.7z 
              .\libjxl-main-native\lib\Release\libjxl.lib
              .\libjxl-main-native\lib\Release\libjxl_threads.lib 
              .\libjxl-main-native\lib\Release\libjxl_cms.lib 
              .\libjxl-main-native\lib\Release\libjpegli-static.lib 
              .\libjxl-main-native\third_party\brotli\Release\libbrotlicommon.lib
              .\libjxl-main-native\third_party\brotli\Release\libbrotlidec.lib 
              .\libjxl-main-native\third_party\brotli\Release\libbrotlienc.lib 
              .\libjxl-main-native\third_party\highway\Release\libhwy.lib

      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          path: libjxl.7z
          name: win
  

  build_on_linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: build-libjxl
        run: ./build-libjxl-linux.sh

      - name: Encrypt
        run: 7z a -t7z -p'${{ secrets.ARTIFACTS_PWD }}' -mhe=on -mx=9 libjxl.7z 
              ./libjxl-main-native/lib/libjxl.a 
              ./libjxl-main-native/lib/libjxl_threads.a
              ./libjxl-main-native/lib/libjxl_cms.a 
              ./libjxl-main-native/lib/libjpegli-static.a 
              ./libjxl-main-native/third_party/brotli/libbrotlicommon.a 
              ./libjxl-main-native/third_party/brotli/libbrotlidec.a 
              ./libjxl-main-native/third_party/brotli/libbrotlienc.a 
              ./libjxl-main-native/third_party/highway/libhwy.a

      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          path: libjxl.7z
          name: linux

  build_on_mac:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: build-libjxl
        run: ./build-libjxl-mac.sh
        
      - name: Encrypt
        run: 7z a -t7z -p'${{ secrets.ARTIFACTS_PWD }}' -mhe=on -mx=9 libjxl.7z 
              ./libjxl-main-native/lib/libjxl.a 
              ./libjxl-main-native/lib/libjxl_threads.a
              ./libjxl-main-native/lib/libjxl_cms.a 
              ./libjxl-main-native/lib/libjpegli-static.a 
              ./libjxl-main-native/third_party/brotli/libbrotlicommon.a 
              ./libjxl-main-native/third_party/brotli/libbrotlidec.a 
              ./libjxl-main-native/third_party/brotli/libbrotlienc.a 
              ./libjxl-main-native/third_party/highway/libhwy.a

      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          path: libjxl.7z
          name: mac


